server:
  port: 50003
  
spring:
  application:
    name: catalog-ws
  profiles:
    active: local      
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console        
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    
  redis:
    lettuce:
      timeout: 1000
      shutdown-timeout: 100
      auto-reconnect: false
      pool:
        max-active: 1   # pool에 할당할수 있는 커넥션 최대수(default:8)
        max-idle: 1     # pool의 idle 커넥션 최대수(default:8)
        min-idle: 0     # pool의 idle 커넥션 최소수(default:0)
      host: 211.43.13.1  #
      port: 32593
     
management:
  endpoints:
    web:
      exposure:
        include: "*"    

logging.level.org.springframework.cloud.sleuth: DEBUG


